#Design an algorithm that generates the first n numbers in the following sequence:; 1, 2, 3, 6, 11, 20, 37, ___, ___, ___, …


#Ask user to enter how many number he wants to see
#store values 1, 2 and 3
# user counter to know how many numbers to add, counter starts as 3 since that is the first new number 
#next number in the seuqence is generated by adding the last three numbers 


n = int(input("Enter the length of the sequence: ")) # Do not change this line
 
num_int_1 = 1
num_int_2 = 2
num_int_3 = 3

counter = 3

print(num_int_1,num_int_2,num_int_3, end= " ")

while counter < n:
    next_int = num_int_1 + num_int_2 + num_int_3
    num_int_1 = num_int_2
    num_int_2 = num_int_3
    num_int_3 = next_int
    counter += 1
    print(next_int, end= " ")