#Design an algorithm that generates the first n numbers in the following sequence:; 1, 2, 3, 6, 11, 20, 37, ___, ___, ___, …


#Ask user to enter how many number he wants to see
#store values 1, 2 and 3 
#next number in the seuqence is generated by adding the last three numbers 
